site_name: ebolasim
theme:
  name: material
plugins:
  - search
  - mkdocs-jupyter:
      execute: true
      include_source: true
      include:
        - "*.ipynb"
        - "**/*.ipynb"
      ignore_h1_titles: false
nav:
  - Getting started: index.ipynb
  - Parameters: parameters.ipynb
  - Single admin unit validation:
      - Overview: vignettes/sadv/comparison.ipynb
      - Evidence summary: vignettes/sadv/evidence/comparison_summary.md
  - Maintainers: maintainers.ipynb
