"""Python-first simulation interface for the EbolaSim C model."""

from __future__ import annotations

import json
import shlex
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from ebolasim_tools.binary import write_density_file
from ebolasim_tools.bundled import resolve_bundled_executable
from ebolasim_tools.command import CommandPlan, build_command_plan
from ebolasim_tools.manifest import (
    ManifestInputs,
    ManifestModelArgs,
    ManifestOutputs,
    ManifestSource,
    RunManifest,
)
from ebolasim_tools.run import RunResult, run_model

from .pars import Pars, demo_pars
from .results import Results, read_results

DEFAULT_SEEDS = (98798150, 729101, 1234567, 7654321)


def resolve_executable(exe: str | Path | None = None, *, required: bool = True) -> Path | None:
    """Resolve an explicit or bundled model executable."""

    if exe is not None:
        path = Path(exe).expanduser().resolve()
        if required and not path.is_file():
            raise FileNotFoundError(path)
        return path
    bundled = resolve_bundled_executable(package_root=Path(__file__).resolve().parent)
    if bundled.ok and bundled.path:
        return Path(bundled.path)
    if required:
        detail = "; ".join(bundled.diagnostics)
        raise FileNotFoundError(
            "No bundled EbolaSim executable is available for this platform. "
            "Install a release wheel with a bundled executable or pass exe=... "
            f"({detail})"
        )
    return None


def _seed_tuple(seed: int | tuple[int, int, int, int] | None) -> tuple[int, int, int, int]:
    if seed is None:
        return DEFAULT_SEEDS
    if isinstance(seed, tuple):
        if len(seed) != 4:
            raise ValueError("seed tuple must contain exactly four integers")
        return tuple(int(item) for item in seed)  # type: ignore[return-value]
    return (int(seed), DEFAULT_SEEDS[1], DEFAULT_SEEDS[2], DEFAULT_SEEDS[3])


def _density_records(
    *, population: int, grid_width: int = 4, admin_units: int = 4
) -> list[tuple[float, float, float, int, int]]:
    records: list[tuple[float, float, float, int, int]] = []
    cell_count = grid_width * grid_width
    base_pop = population // cell_count
    remainder = population % cell_count
    for y in range(grid_width):
        for x in range(grid_width):
            index = y * grid_width + x
            records.append(
                (
                    (x + 0.5) / grid_width,
                    (y + 0.5) / grid_width,
                    float(base_pop + (1 if index < remainder else 0)),
                    1,
                    1 + (index % admin_units),
                )
            )
    return records


@dataclass
class Sim:
    """A runnable EbolaSim scenario."""

    pars: Pars = field(default_factory=demo_pars)
    label: str = "demo"
    outdir: str | Path = "runs/demo"
    threads: int = 1
    seed: int | tuple[int, int, int, int] | None = None
    exe: str | Path | None = None
    results: Results | None = None
    run_result: RunResult | None = None

    @property
    def root(self) -> Path:
        return Path(self.outdir).expanduser().resolve()

    @property
    def input_dir(self) -> Path:
        return self.root / "inputs"

    @property
    def output_dir(self) -> Path:
        return self.root / "outputs"

    @property
    def summary(self) -> dict[str, Any] | None:
        return None if self.results is None else self.results.summary

    @property
    def returncode(self) -> int | None:
        return None if self.run_result is None else self.run_result.returncode

    @property
    def stdout(self) -> str:
        if self.run_result is None:
            return ""
        return Path(self.run_result.stdout_path).read_text(encoding="utf-8", errors="replace")

    @property
    def stderr(self) -> str:
        if self.run_result is None:
            return ""
        return Path(self.run_result.stderr_path).read_text(encoding="utf-8", errors="replace")

    def _prepare_inputs(self) -> RunManifest:
        self.input_dir.mkdir(parents=True, exist_ok=True)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        parameter_file = self.input_dir / "parameters.txt"
        preparameter_file = self.input_dir / "preparameters.txt"
        density_file = self.input_dir / "population.bin"
        network_file = self.input_dir / "network.bin"
        self.pars.write(parameter_file)
        preparameter_file.write_text(
            "[Scenario name]\nDemoDistrict\n[Generated by]\nebolasim\n", encoding="utf-8"
        )
        population = self.pars.raw.get_int("Population size", 24) or 24
        write_density_file(density_file, _density_records(population=population))
        if not network_file.exists():
            network_file.write_bytes(b"")
        return RunManifest(
            inputs=ManifestInputs(
                parameter_file=parameter_file.relative_to(self.root).as_posix(),
                preparameter_file=preparameter_file.relative_to(self.root).as_posix(),
                density_file=density_file.relative_to(self.root).as_posix(),
                network_file=network_file.relative_to(self.root).as_posix(),
                network_mode="save",
            ),
            outputs=ManifestOutputs(
                output_base=(self.output_dir / self.label).relative_to(self.root).as_posix(),
                output_dir=self.output_dir.relative_to(self.root).as_posix(),
            ),
            threads=self.threads,
            executable="ebola-spatial-linux",
            model_args=ManifestModelArgs(r0_scale="1.0", clp={1: "0", 2: "0"}),
            seeds=list(_seed_tuple(self.seed)),
            source=ManifestSource(kind="demo", bundle_root="."),
            metadata={"label": self.label, "api": "ebolasim.Sim"},
        )

    def command(self) -> CommandPlan:
        manifest = self._prepare_inputs()
        exe = resolve_executable(self.exe, required=False)
        return build_command_plan(
            manifest,
            executable=exe or self.exe or "ebola-spatial-linux",
            root=self.root,
            working_directory=self.root,
            threads=self.threads,
        )

    def write_script(self, path: str | Path) -> Path:
        plan = self.command()
        target = Path(path)
        target.parent.mkdir(parents=True, exist_ok=True)
        lines = ["#!/usr/bin/env bash", "set -euo pipefail"]
        for key, value in plan.environment.items():
            lines.append(f"export {key}={shlex.quote(value)}")
        lines.append(f"cd {shlex.quote(plan.working_directory or self.root.as_posix())}")
        lines.append(shlex.join(plan.command))
        target.write_text("\n".join(lines) + "\n", encoding="utf-8")
        target.chmod(target.stat().st_mode | 0o111)
        return target

    def run(self, *, timeout: int | float | None = None) -> Sim:
        manifest = self._prepare_inputs()
        executable = resolve_executable(self.exe)
        result = run_model(
            manifest,
            executable=executable,
            root=self.root,
            run_dir=self.root / "logs",
            timeout=timeout,
            threads=self.threads,
        )
        self.run_result = result
        if result.ok:
            self.results = read_results(result.output_dir)
        return self

    def plot(self, **kwargs: Any) -> Any:
        if self.results is None:
            raise ValueError("run the simulation or attach results before plotting")
        return self.results.plot(**kwargs)

    def to_json(self, *, pretty: bool = False) -> str:
        payload = {
            "label": self.label,
            "outdir": self.root.as_posix(),
            "threads": self.threads,
            "summary": self.summary,
            "returncode": self.returncode,
        }
        return json.dumps(payload, indent=2 if pretty else None, sort_keys=True)


__all__ = ["Sim", "resolve_executable"]
